INSERT INTO `magnitudes` (`id`, `idmagnitude`, `magnitude`, `description`, `high`, `low`, `created_at`, `updated_at`, `deleted_at`, `idunit_id`) VALUES
	(1, 0, 'TIN', 'Temperatura interna', 40, 10, NULL, NULL, NULL, 4),
	(2, 1, 'SO2', 'Dióxido de Azufre', 30, 0, NULL, NULL, NULL, 2),
	(3, 2, 'HNN', 'Humo negro', NULL, NULL, NULL, NULL, NULL, 2),
	(4, 3, 'SPM', 'Partículas en suspensión', NULL, NULL, NULL, NULL, NULL, 2),
	(5, 4, 'AF', 'Acidez Fuerte', NULL, NULL, NULL, NULL, NULL, 39),
	(6, 5, 'CO2', 'Dióxido de Carbono', NULL, NULL, NULL, NULL, NULL, 6),
	(7, 6, 'CO', 'Monóxido de Carbono', 10, 0, NULL, NULL, NULL, 6),
	(8, 7, 'NO', 'Monóxido de Nitrógeno', 400, 0, NULL, NULL, NULL, 2),
	(9, 8, 'NO2', 'Dióxido de Nitrógeno', 300, 0, NULL, NULL, NULL, 2),
	(10, 9, 'PM2.5', 'Partículas en suspensión (< 2.5 µm)', 350, 0, NULL, NULL, NULL, 2),
	(11, 10, 'PM10', 'Partículas en suspensión (< 10 µm)', 350, 0, NULL, NULL, NULL, 2),
	(12, 11, 'PM1', 'Partículas en suspensión (< 1 µm)', NULL, NULL, NULL, NULL, NULL, 2),
	(13, 12, 'NOX', 'Oxidos de Nitrógeno totales', NULL, NULL, NULL, NULL, NULL, 2),
	(14, 14, 'O3', 'Ozono', 240, 0, NULL, NULL, NULL, 2),
	(15, 15, 'Cr', 'Cromo', NULL, NULL, NULL, NULL, NULL, 2),
	(16, 16, 'Mn', 'Manganeso', NULL, NULL, NULL, NULL, NULL, 2),
	(17, 17, 'As', 'Arsénico', 6, 0, NULL, NULL, NULL, 2),
	(18, 18, 'A-', 'Aniones', NULL, NULL, NULL, NULL, NULL, 2),
	(19, 19, 'Pb', 'Plomo', 1, 0, NULL, NULL, NULL, 2),
	(20, 20, 'Tol', 'Tolueno', 30, 0, NULL, NULL, NULL, 2),
	(21, 21, 'Est', 'Estireno', NULL, NULL, NULL, NULL, NULL, 2),
	(22, 22, 'BCAR', 'Black Carbon', NULL, NULL, NULL, NULL, NULL, 2),
	(23, 23, 'HCHO', 'Formaldehido', NULL, NULL, NULL, NULL, NULL, 2),
	(24, 24, '3ClE', 'Tricloroetileno', NULL, NULL, NULL, NULL, NULL, 2),
	(25, 25, '4ClE', 'Tetracloroetileno', NULL, NULL, NULL, NULL, NULL, 2),
	(26, 26, '2ClM', 'Diclorometano', NULL, NULL, NULL, NULL, NULL, 2),
	(27, 27, 'BaP', 'Benzo(a)pireno', 1, 0, NULL, NULL, NULL, 2),
	(28, 28, 'Cd', 'Partículas de Cadmio', 5, 0, NULL, NULL, NULL, 2),
	(29, 29, 'CV', 'Cloruro de vinilo', NULL, NULL, NULL, NULL, NULL, 2),
	(30, 30, 'Ben', 'Benzeno', 10, 0, NULL, NULL, NULL, 2),
	(31, 31, 'Xil', 'Xileno', 30, 0, NULL, NULL, NULL, 2),
	(32, 32, 'PAN', 'Nitrato de peroxiacetilo', NULL, NULL, NULL, NULL, NULL, 2),
	(33, 33, 'Ndep', 'Depósito húmedo-nitrógeno', NULL, NULL, NULL, NULL, NULL, 2),
	(34, 34, 'Sdep', 'Depósito húmedo-azufre', NULL, NULL, NULL, NULL, NULL, 2),
	(35, 35, 'C8H10', 'Etilbenceno', NULL, NULL, NULL, NULL, NULL, 2),
	(36, 36, 'C4H6', 'Butadieno', NULL, NULL, NULL, NULL, NULL, 2),
	(37, 37, 'M-XIL', 'Metaxileno', NULL, NULL, NULL, NULL, NULL, 2),
	(38, 38, 'P-XIL', 'Paraxileno', NULL, NULL, NULL, NULL, NULL, 2),
	(39, 39, 'O-XIL', 'Ortoxileno', NULL, NULL, NULL, NULL, NULL, 2),
	(40, 42, 'HCT', 'Hidrocarburos gaseosos totales', 60, 0, NULL, NULL, NULL, 6),
	(41, 43, 'CH4', 'Metano', NULL, NULL, NULL, NULL, NULL, 6),
	(42, 44, 'NMH', 'Hidrocarburos gaseosos no metánicos', 60, 0, NULL, NULL, NULL, 6),
	(43, 50, 'PSD', 'Partículas sedimentables', NULL, NULL, NULL, NULL, NULL, 2),
	(44, 51, 'HAP', 'Hidrocarb. aromáticos policíclicos', NULL, NULL, NULL, NULL, NULL, 6),
	(45, 52, 'VOC', 'Compuestos orgánicos volátiles', NULL, NULL, NULL, NULL, NULL, 2),
	(46, 53, 'Cl2', 'Cloro molecular', NULL, NULL, NULL, NULL, NULL, 39),
	(47, 54, 'FH', 'Fluoruro de hidrógeno', NULL, NULL, NULL, NULL, NULL, 39),
	(48, 55, 'Cl-', 'Cloruros', NULL, NULL, NULL, NULL, NULL, 39),
	(49, 56, 'Fl-', 'Fluoruros', NULL, NULL, NULL, NULL, NULL, 39),
	(50, 57, 'Br-', 'Bromuros', NULL, NULL, NULL, NULL, NULL, 39),
	(51, 58, 'HCl', 'Acido clorhídrico', NULL, NULL, NULL, NULL, NULL, 39),
	(52, 59, 'Cu', 'Cobre', NULL, NULL, NULL, NULL, NULL, 2),
	(53, 60, 'Fe', 'Hierro', NULL, NULL, NULL, NULL, NULL, 2),
	(54, 61, 'Mn', 'Manganeso', NULL, NULL, NULL, NULL, NULL, 2),
	(55, 62, 'Ni', 'Níquel', 20, 0, NULL, NULL, NULL, 2),
	(56, 63, 'NH3', 'Amoníaco', NULL, NULL, NULL, NULL, NULL, 2),
	(57, 64, 'HCP', 'Hidrocarburos petrolígenos', NULL, NULL, NULL, NULL, NULL, 6),
	(58, 65, 'SH2', 'Sulfuro de hidrógeno', NULL, NULL, NULL, NULL, NULL, 2),
	(59, 66, 'TRS', 'Compuestos reducidos de azufre totales', NULL, NULL, NULL, NULL, NULL, 39),
	(60, 68, 'ASB', 'Asbestos', NULL, NULL, NULL, NULL, NULL, 2),
	(61, 70, 'Rui', 'Nivel sonoro equivalente', NULL, NULL, NULL, NULL, NULL, 32),
	(62, 81, 'VV', 'Velocidad de viento', 25, 0, NULL, NULL, NULL, 9),
	(63, 82, 'DD', 'Dirección de viento', 360, 0, NULL, NULL, NULL, 8),
	(64, 83, 'TMP', 'Temperatura media', 50, -10, NULL, NULL, NULL, 4),
	(65, 84, 'TMX', 'Temperatura máxima', NULL, NULL, NULL, NULL, NULL, 4),
	(66, 85, 'TMI', 'Temperatura mínima', NULL, NULL, NULL, NULL, NULL, 4),
	(67, 86, 'HR', 'Humedad relativa', 110, 0, NULL, NULL, NULL, 34),
	(68, 87, 'PRB', 'Presión barométrica', 1200, 800, NULL, NULL, NULL, 35),
	(69, 88, 'RS', 'Radiación solar', 1100, 0, NULL, NULL, NULL, 15),
	(70, 89, 'LL', 'Precipitación', 5, 0, NULL, NULL, NULL, 18),
	(71, 90, 'EST', 'Estabilidad', NULL, NULL, NULL, NULL, NULL, 39),
	(72, 92, 'UV-B', 'Radiación Ultravioleta', NULL, NULL, NULL, NULL, NULL, 15),
	(73, 93, 'TH', 'Tiempo de humectación', NULL, NULL, NULL, NULL, NULL, 39),
	(74, 101, 'O2', 'Oxígeno', NULL, NULL, NULL, NULL, NULL, 7),
	(75, 102, 'HUM', 'Humedad de gases', NULL, NULL, NULL, NULL, NULL, 39),
	(76, 103, 'Ves', 'Volumen estequiométrico seco', NULL, NULL, NULL, NULL, NULL, 40),
	(77, 104, 'PWR', 'Potencia', NULL, NULL, NULL, NULL, NULL, 3),
	(78, 105, 'MAS', 'Cantidad de combustible', NULL, NULL, NULL, NULL, NULL, 24),
	(79, 106, 'NIE', 'Altura de nieve', NULL, NULL, NULL, NULL, NULL, 41),
	(80, 107, 'CAU', 'Caudal', NULL, NULL, NULL, NULL, NULL, 18),
	(81, 110, 'FLJ', 'Flujo de agua', NULL, NULL, NULL, NULL, NULL, 42),
	(82, 120, 'TMA', 'Temperatura del Agua', NULL, NULL, NULL, NULL, NULL, 4),
	(83, 121, 'OXI', 'Oxígeno Disuelto', NULL, NULL, NULL, NULL, NULL, 22),
	(84, 122, 'CND', 'Conductividad', NULL, NULL, NULL, NULL, NULL, 13),
	(85, 123, 'TUR', 'Turbidez', NULL, NULL, NULL, NULL, NULL, 14),
	(86, 124, 'pH', 'pH - Grado de Acidez', NULL, NULL, NULL, NULL, NULL, 53),
	(87, 125, 'PRX', 'Potencial Redox', NULL, NULL, NULL, NULL, NULL, 54),
	(88, 126, 'PRF', 'Profundidad', NULL, NULL, NULL, NULL, NULL, 55),
	(89, 127, 'FOS', 'Fosfatos', NULL, NULL, NULL, NULL, NULL, 22),
	(90, 128, 'P', 'Fósforo', NULL, NULL, NULL, NULL, NULL, 22),
	(91, 129, 'DvstVV', 'Desviación Típica Velocidad de viento', NULL, NULL, NULL, NULL, NULL, 9),
	(92, 130, 'DvstDD', 'Desviación Típica Dirección de viento', NULL, NULL, NULL, NULL, NULL, 8),
	(93, 152, 'HR Int', 'Humedad Relativa Interior', NULL, NULL, NULL, NULL, NULL, 34),
	(94, 215, 'PST 10', 'Partículas Totales < 10 µm', NULL, NULL, NULL, NULL, NULL, 2),
	(95, 251, 'TCAB', 'Temperatura Cabina', NULL, NULL, NULL, NULL, NULL, 4),
	(96, 252, 'GL', 'Radiación Global', NULL, NULL, NULL, NULL, NULL, 15),
	(97, 253, 'DF', 'Radiación Difusa', NULL, NULL, NULL, NULL, NULL, 15),
	(98, 254, 'DT', 'Radiación Directa', NULL, NULL, NULL, NULL, NULL, 15),
	(99, 255, 'PAR', 'Photosintetic Active Radiation Lite', NULL, NULL, NULL, NULL, NULL, 45),
	(100, 256, 'IR', 'Radiación Infraroja', NULL, NULL, NULL, NULL, NULL, 43),
	(101, 257, 'UV-A', 'Radiación Ultravioleta A', NULL, NULL, NULL, NULL, NULL, 43),
	(102, 258, 'UV-B', 'Radiación Ultravioleta B', NULL, NULL, NULL, NULL, NULL, 43),
	(103, 259, 'GL DKJul', 'Radiación Global DKJulios', NULL, NULL, NULL, NULL, NULL, 44),
	(104, 260, 'DF DKJul', 'Radiación Difusa DKJulios', NULL, NULL, NULL, NULL, NULL, 44),
	(105, 261, 'DT DKJul', 'Radiación Directa DKJulios', NULL, NULL, NULL, NULL, NULL, 44),
	(106, 262, 'PAR DKJul', 'Photosintetic Active Radiation Lite DKJulios', NULL, NULL, NULL, NULL, NULL, 46),
	(107, 263, 'IR DKJul', 'Radiación Infraroja DKJulios', NULL, NULL, NULL, NULL, NULL, 44),
	(108, 264, 'UV-A DKJul', 'Radiación Ultravioleta A', NULL, NULL, NULL, NULL, NULL, 44),
	(109, 265, 'UV-B DKJul', 'Radiación Ultravioleta B DKJulios', NULL, NULL, NULL, NULL, NULL, 44),
	(110, 266, 'UVI', 'Índice Ultravioleta B', NULL, NULL, NULL, NULL, NULL, 39),
	(111, 301, 'NH4', 'Amonio', NULL, NULL, NULL, NULL, NULL, 47),
	(112, 302, 'COT', 'Contaminación Total', NULL, NULL, NULL, NULL, NULL, 48),
	(113, 303, 'PRFE', 'Profundidad Externa', NULL, NULL, NULL, NULL, NULL, 10),
	(114, 304, 'TUREXT', 'Turbidez Externa', NULL, NULL, NULL, NULL, NULL, 14),
	(115, 305, 'OXI mg', 'Oxígeno Disuelto mg/l', NULL, NULL, NULL, NULL, NULL, 22),
	(116, 310, 'COD', 'Carbono Orgánico Disuelto', NULL, NULL, NULL, NULL, NULL, 50),
	(117, 311, 'NO3-', 'Nitratos', NULL, NULL, NULL, NULL, NULL, 51),
	(118, 312, 'CNDA', 'Conductividad Alto Rango', NULL, NULL, NULL, NULL, NULL, 13),
	(119, 313, 'COLITO', 'Coliformes totales', NULL, NULL, NULL, NULL, NULL, 52),
	(120, 314, 'COLFE', 'Coliformes fecales', NULL, NULL, NULL, NULL, NULL, 52),
	(121, 315, 'ESTREP', 'Estreptococos fecales', NULL, NULL, NULL, NULL, NULL, 52),
	(122, 316, 'SALMO', 'Salmonella', NULL, NULL, NULL, NULL, NULL, 52),
	(123, 317, 'ENTERO', 'Enterovirus', NULL, NULL, NULL, NULL, NULL, 52),
	(124, 318, 'COLOR', 'Color', NULL, NULL, NULL, NULL, NULL, 39),
	(125, 319, 'ACEITES', 'Aceites Minerales', NULL, NULL, NULL, NULL, NULL, 39),
	(126, 320, 'TENSOACTIVAS', 'Sustancias tensoactivas', NULL, NULL, NULL, NULL, NULL, 39),
	(127, 321, 'FENOLES', 'Fenoles', NULL, NULL, NULL, NULL, NULL, 39),
	(128, 322, 'TRANSPARENCIA', 'Transparencia', NULL, NULL, NULL, NULL, NULL, 39),
	(129, 323, 'ALQUITRAN', 'Residuos alquitranados', NULL, NULL, NULL, NULL, NULL, 39),
	(130, 324, 'SOSUSP', 'Sólidos en suspensión', NULL, NULL, NULL, NULL, NULL, 22),
	(131, 325, 'DBO', 'Demanda bioquímica oxígeno', NULL, NULL, NULL, NULL, NULL, 56),
	(132, 326, 'SO4', 'Sulfatos', NULL, NULL, NULL, NULL, NULL, 22),
	(133, 327, 'Zn', 'Cinc', NULL, NULL, NULL, NULL, NULL, 22),
	(134, 328, 'Ba', 'Bario', NULL, NULL, NULL, NULL, NULL, 22),
	(135, 329, 'Se', 'Selenio', NULL, NULL, NULL, NULL, NULL, 22),
	(136, 330, 'Bo', 'Boro', NULL, NULL, NULL, NULL, NULL, 22),
	(137, 331, 'Hg', 'Mercurio', NULL, NULL, NULL, NULL, NULL, 2),
	(138, 332, 'Nitritos', 'Nitritos', NULL, NULL, NULL, NULL, NULL, 57),
	(139, 333, 'Cl residual', 'Cloro residual total', NULL, NULL, NULL, NULL, NULL, 58),
	(140, 334, 'MATORG', 'Materia orgánica', NULL, NULL, NULL, NULL, NULL, 48),
	(141, 335, 'UV-E', 'UV Eritemal', NULL, NULL, NULL, NULL, NULL, 15),
	(142, 336, 'O2-E', 'Oxígeno de emisión', NULL, NULL, NULL, NULL, NULL, 7),
	(143, 337, 'CO2-E', 'Dióxido de carbono de emisión', NULL, NULL, NULL, NULL, NULL, 7),
	(144, 338, 'NOx-E', 'Óxidos de nitrógeno totales de emisión', NULL, NULL, NULL, NULL, NULL, 47),
	(145, 339, 'CO-E', 'Monóxido de carbono de emisión', NULL, NULL, NULL, NULL, NULL, 47),
	(146, 340, 'SO2-E', 'Dióxido de azufre de emisión', NULL, NULL, NULL, NULL, NULL, 47),
	(147, 341, 'PST-E', 'Partículas de emisión', NULL, NULL, NULL, NULL, NULL, 6),
	(148, 342, 'Caudal-E', 'Caudal de gases de emisión', NULL, NULL, NULL, NULL, NULL, 59),
	(149, 343, 'Flujo', 'Flujo combustible', NULL, NULL, NULL, NULL, NULL, 20),
	(150, 344, 'Carga', 'Carga eléctrica', NULL, NULL, NULL, NULL, NULL, 3),
	(151, 345, 'DOF', 'Flujo de aceite destilado', NULL, NULL, NULL, NULL, NULL, 61),
	(152, 346, 'CAU-E', 'Caudal de agua de emisión', NULL, NULL, NULL, NULL, NULL, 61),
	(153, 347, 'PRB-E', 'Presión de gases de emisión', NULL, NULL, NULL, NULL, NULL, 62),
	(154, 348, 'TMP-E', 'Temperatura de gases de emisión', NULL, NULL, NULL, NULL, NULL, 4),
	(155, 349, 'O2H-E', 'Oxígeno húmedo de emisión', NULL, NULL, NULL, NULL, NULL, 7),
	(156, 350, 'LAT', 'Latitud', NULL, NULL, NULL, NULL, NULL, 63),
	(157, 351, 'LON', 'Longitud', NULL, NULL, NULL, NULL, NULL, 63),
	(158, 352, 'LPO2', 'Lectura de dioxido de un patron de 2 ppp', NULL, NULL, NULL, NULL, NULL, 39),
	(159, 353, 'MST', 'Materias sedimentables totales', NULL, NULL, NULL, NULL, NULL, 36),
	(160, 354, 'MSI', 'Materias sedimentables insolubles', NULL, NULL, NULL, NULL, NULL, 36),
	(161, 355, 'MSS', 'Materias sedimentables solubles', NULL, NULL, NULL, NULL, NULL, 36),
	(162, 356, 'BCB', 'Bicarbonatos', NULL, NULL, NULL, NULL, NULL, 36),
	(163, 357, 'Na', 'Sodio', NULL, NULL, NULL, NULL, NULL, 36),
	(164, 358, 'K', 'Potasio', NULL, NULL, NULL, NULL, NULL, 36),
	(165, 359, 'Ca', 'Calcio', NULL, NULL, NULL, NULL, NULL, 36),
	(166, 360, 'Mg', 'Magnesio', NULL, NULL, NULL, NULL, NULL, 36),
	(167, 361, 'Fia', 'Fiabilidad', NULL, NULL, NULL, NULL, NULL, 39),
	(168, 362, 'Cpt', 'Capacidad', NULL, NULL, NULL, NULL, NULL, 64),
	(169, 363, 'NGC CO2', 'Natural Gas Composition CO2', NULL, NULL, NULL, NULL, NULL, 37),
	(170, 364, 'NGC N2', 'Natural Gas Composition N2', NULL, NULL, NULL, NULL, NULL, 37),
	(171, 365, 'NGC C', 'Natural Gas Composition C', NULL, NULL, NULL, NULL, NULL, 37),
	(172, 366, 'NGC C2', 'Natural Gas Composition C2', NULL, NULL, NULL, NULL, NULL, 37),
	(173, 367, 'NGC C3', 'Natural Gas Composition C3', NULL, NULL, NULL, NULL, NULL, 37),
	(174, 368, 'NGC iC4', 'Natural Gas Composition iC4', NULL, NULL, NULL, NULL, NULL, 37),
	(175, 369, 'NGC nC4', 'Natural Gas Composition nC4', NULL, NULL, NULL, NULL, NULL, 37),
	(176, 370, 'NGC iC5', 'Natural Gas Composition iC5', NULL, NULL, NULL, NULL, NULL, 37),
	(177, 371, 'NGC nC5', 'Natural Gas Composition nC5', NULL, NULL, NULL, NULL, NULL, 37),
	(178, 372, 'NGC neoC5', 'Natural Gas Composition neoCO5', NULL, NULL, NULL, NULL, NULL, 37),
	(179, 373, 'NGC C6+', 'Natural Gas Composition C6+', NULL, NULL, NULL, NULL, NULL, 37),
	(180, 374, 'NGRD', 'Natural Gas Relativity Density', NULL, NULL, NULL, NULL, NULL, 37),
	(181, 375, 'GT1GP', 'GT1 Gross Power', NULL, NULL, NULL, NULL, NULL, 2),
	(182, 376, 'GT2GP', 'GT2 Gross Power', NULL, NULL, NULL, NULL, NULL, 2),
	(183, 377, 'STGP', 'ST Gross Power', NULL, NULL, NULL, NULL, NULL, 2),
	(184, 378, 'GT1PE', 'GT1 Power Export', NULL, NULL, NULL, NULL, NULL, 2),
	(185, 379, 'GT2PE', 'GT2 Power Export', NULL, NULL, NULL, NULL, NULL, 2),
	(186, 380, 'STPE', 'ST Power Export', NULL, NULL, NULL, NULL, NULL, 2),
	(187, 381, 'TPE', 'Total Plan Efficiency', NULL, NULL, NULL, NULL, NULL, 39),
	(188, 382, 'GT1OH', 'GT1 Operating Hours', NULL, NULL, NULL, NULL, NULL, 65),
	(189, 383, 'GT2OH', 'GT2 Operating Hours', NULL, NULL, NULL, NULL, NULL, 65),
	(190, 384, 'STOH', 'ST Operating Hours', NULL, NULL, NULL, NULL, NULL, 65),
	(191, 385, 'TNGI', 'Total Natural Gas Import', NULL, NULL, NULL, NULL, NULL, 66),
	(192, 386, 'EGF HRSG1', 'Exhuaust Gas Flow HRSG1', NULL, NULL, NULL, NULL, NULL, 66),
	(193, 387, 'EGF HRSG2', 'Exhuaust Gas Flow HRSG2', NULL, NULL, NULL, NULL, NULL, 66),
	(194, 388, 'NG HHV', 'Natural Gas HHV', NULL, NULL, NULL, NULL, NULL, 67),
	(195, 389, 'NG LHV', 'Natural Gas LHV', NULL, NULL, NULL, NULL, NULL, 67),
	(196, 390, 'Tmp Sensor', 'Temperatura Sensor', NULL, NULL, NULL, NULL, NULL, 4),
	(197, 431, 'MPXIL', 'MetaParaXileno', NULL, NULL, NULL, NULL, NULL, 2),
	(198, 501, 'ID_TCAM', 'Temperatura cámara', NULL, NULL, NULL, NULL, NULL, 4),
	(199, 502, 'ID_TCOO', 'Temperatura cooler', NULL, NULL, NULL, NULL, NULL, 4),
	(200, 503, 'ID_TCON', 'Temp. Convertidor', NULL, NULL, NULL, NULL, NULL, 4),
	(201, 504, 'ID_TAMB', 'Temp. Ambiente', NULL, NULL, NULL, NULL, NULL, 4),
	(202, 505, 'ID_TMUESTRA', 'Temp. Muestra', NULL, NULL, NULL, NULL, NULL, 4),
	(203, 506, 'ID_PCAM', 'Presión cámara', NULL, NULL, NULL, NULL, NULL, 12),
	(204, 507, 'ID_PAMB', 'Presión ambiente', NULL, NULL, NULL, NULL, NULL, 12),
	(205, 511, 'ID_FLWM', 'Caudal', NULL, NULL, NULL, NULL, NULL, 68),
	(206, 521, 'ID_HV', 'Alta tensión', NULL, NULL, NULL, NULL, NULL, 38),
	(207, 522, 'ID_VRF1', 'Tensión interna de referencia 1', NULL, NULL, NULL, NULL, NULL, 38),
	(208, 523, 'ID_VRF2', 'Tensión interna de referencia 2', NULL, NULL, NULL, NULL, NULL, 38),
	(209, 531, 'ID_SA1', 'Salida analógica 1', NULL, NULL, NULL, NULL, NULL, 38),
	(210, 532, 'ID_SA2', 'Salida analógica 2', NULL, NULL, NULL, NULL, NULL, 38),
	(211, 533, 'ID_SA3', 'Salida analógica 3', NULL, NULL, NULL, NULL, NULL, 38),
	(212, 534, 'ID_SA4', 'Salida analógica 4', NULL, NULL, NULL, NULL, NULL, 38),
	(213, 542, 'ID_POWER', 'Alarma de hora de arranque/parada', NULL, NULL, NULL, NULL, NULL, 39),
	(214, 543, 'ID_CERO', 'Alarma de comienzo de calibración de cero', NULL, NULL, NULL, NULL, NULL, 39),
	(215, 544, 'ID_SPAN', 'Alarma de comienzo de calibración de span', NULL, NULL, NULL, NULL, NULL, 39),
	(216, 1000, 'PUERTA', 'Alarma de puerta abierta', NULL, NULL, NULL, NULL, NULL, 39),
	(217, 1001, 'INCENDIO', 'Alarma de incendio', NULL, NULL, NULL, NULL, NULL, 39),
	(218, 1002, 'ACCESO', 'Alarma de acceso', NULL, NULL, NULL, NULL, NULL, 39);

