INSERT INTO `marks` (`id`, `mark`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES
	(1, 'Desconocido', 'Desconocido', NULL, NULL, NULL),
	(2, 'Aire Acondicionado Genérico', 'null', NULL, NULL, NULL),
	(3, 'Gast - IDEX Corp.', 'http://www.gastmfg.com/', NULL, NULL, NULL),
	(4, 'Abelló Linde S.A.', 'http://www.abello-linde-sa.es', NULL, NULL, NULL),
	(5, 'Teldat', 'http://www.teldat.com', NULL, NULL, NULL),
	(7, 'DASIBI', 'Dasibi Corporation', NULL, NULL, NULL),
	(8, 'SIR S.A.', 'Sistemas', NULL, NULL, NULL),
	(10, 'Grimm Aerosol Technik GmbH & Co.', 'http://www.grimm-aerosol.com', NULL, NULL, NULL),
	(11, 'Coastal Environmental System', 'Coastal Environmental Systems', NULL, NULL, NULL),
	(12, 'DATATAKER', 'DATATAKER', NULL, NULL, NULL),
	(13, 'THIES', 'THIES', NULL, NULL, NULL),
	(14, 'BREWER', 'BREWER', NULL, NULL, NULL),
	(15, 'CIMEL', 'CIMEL', NULL, NULL, NULL),
	(16, 'GEONICA', 'GEONICA', NULL, NULL, NULL),
	(17, 'AEROQUAL', 'AEROQUAL', NULL, NULL, NULL),
	(18, 'Audiotel', 'null', NULL, NULL, NULL),
	(19, 'Texa', 'null', NULL, NULL, NULL),
	(20, 'Salicru', 'http://www.salicru.com', NULL, NULL, NULL),
	(21, 'Campbell Scientific', 'http://www.campbellsci.co.uk', NULL, NULL, NULL),
	(23, 'Wavecom', 'null', NULL, NULL, NULL),
	(24, 'Emersonn Chloride', 'null', NULL, NULL, NULL),
	(25, 'Hanns G', 'null', NULL, NULL, NULL),
	(26, 'Cisco', 'null', NULL, NULL, NULL),
	(27, 'Thomas', 'Gardner Denver', NULL, NULL, NULL),
	(28, 'Multitech', 'null', NULL, NULL, NULL),
	(30, 'Casella Measurement', 'http://casella-es.com/index.php', NULL, NULL, NULL),
	(32, 'Ecotech', 'http://ecotech.com/', NULL, NULL, NULL),
	(33, 'Environnement S.A.', 'http://www.environnement-sa.com', NULL, NULL, NULL),
	(34, 'Horiba Ltd', 'http://www.horiba.com/es', NULL, NULL, NULL),
	(35, 'TM Electronics (UK)', 'http://www.tmelectronics.co.uk', NULL, NULL, NULL),
	(36, 'Teledyne Monitor Labs', 'http://www.teledyne-ml.com', NULL, NULL, NULL),
	(37, 'Sensortechnics GmbH', 'http://www.sensortechnics.com', NULL, NULL, NULL),
	(38, 'Thermo Scientific', 'https://www.thermo.com/com/cda/home', NULL, NULL, NULL),
	(39, 'Vaisala', 'http://es.vaisala.com/sp/Pages/default.aspx', NULL, NULL, NULL),
	(40, 'SRI', 'http://www.icon-sa.com/Cromatografo%20en%20fase%20', NULL, NULL, NULL),
	(41, 'Electronicas Boar S. A.', 'null', NULL, NULL, NULL),
	(42, 'Mundoclima', 'http://www.industrialclima.es/mundoclima.html', NULL, NULL, NULL),
	(43, 'Digitel', 'null', NULL, NULL, NULL),
	(44, 'MCV', 'www.mcvsa.com', NULL, NULL, NULL),
	(45, 'R.M. Young Company', 'http://www.youngusa.com/', NULL, NULL, NULL),
	(46, 'Yankee Environmental System', 'INC', NULL, NULL, NULL),
	(47, 'Hukseflux Thermal Sensors', 'http://www.hukseflux.com', NULL, NULL, NULL),
	(48, 'Hiyasu', 'http://www.hiyasu.com/', NULL, NULL, NULL),
	(49, 'Samsung', 'http://www.samsung.com/es/consumer/home-appliances', NULL, NULL, NULL),
	(50, 'LG', 'http://www.lg.com/es/index.jsp', NULL, NULL, NULL),
	(51, 'Skye Instruments', 'http://www.skyeinstruments.com/', NULL, NULL, NULL),
	(52, 'Crafft Europe Ltd.', 'http://www.craffteurope.com/', NULL, NULL, NULL),
	(53, 'Theodor Friedrichs ', 'http://www.th-friedrichs.de/', NULL, NULL, NULL),
	(54, 'Cesva', 'http://www.cesva.com', NULL, NULL, NULL),
	(55, 'API', 'null', NULL, NULL, NULL),
	(56, 'PANASONIC', 'null', NULL, NULL, NULL),
	(57, 'SAD-PC', 'null', NULL, NULL, NULL),
	(58, 'EQUATION', 'null', NULL, NULL, NULL),
	(59, 'Fujitsu', 'null', NULL, NULL, NULL),
	(60, 'ACER', 'null', NULL, NULL, NULL),
	(61, 'AIR LIQUIDE', 'null', NULL, NULL, NULL),
	(62, 'ALINE SL', 'null', NULL, NULL, NULL),
	(63, 'ALPHAPAZ', 'null', NULL, NULL, NULL),
	(64, 'ANDERSEN INSTRUMENT INCORPORATED', 'null', NULL, NULL, NULL),
	(65, 'APC', 'null', NULL, NULL, NULL),
	(66, 'AQPROX', 'null', NULL, NULL, NULL),
	(67, 'ARTROM', 'null', NULL, NULL, NULL),
	(68, 'BELINEA', 'null', NULL, NULL, NULL),
	(69, 'BENQ', 'null', NULL, NULL, NULL),
	(70, 'BGI INCORPORATED', 'null', NULL, NULL, NULL),
	(71, 'BOARD', 'null', NULL, NULL, NULL),
	(72, 'BRAND GMBH', 'null', NULL, NULL, NULL),
	(73, 'CAREL', 'null', NULL, NULL, NULL),
	(74, 'CHERRY', 'null', NULL, NULL, NULL),
	(75, 'DELL', 'null', NULL, NULL, NULL),
	(76, 'DELTA ELECTRONICS', 'null', NULL, NULL, NULL),
	(77, 'Delta Power Solutions', 'null', NULL, NULL, NULL),
	(78, 'DERENDA', 'null', NULL, NULL, NULL),
	(79, 'DIGITRON', 'null', NULL, NULL, NULL),
	(80, 'DKM', 'null', NULL, NULL, NULL),
	(81, 'E+E ELEKTRONIK', 'null', NULL, NULL, NULL),
	(82, 'EATON', 'null', NULL, NULL, NULL),
	(83, 'Elitech', 'null', NULL, NULL, NULL),
	(84, 'EMERSON', 'null', NULL, NULL, NULL),
	(85, 'EURITECSA', 'null', NULL, NULL, NULL),
	(86, 'FLUKE', 'null', NULL, NULL, NULL),
	(87, 'FUJI ELECTRIC', 'null', NULL, NULL, NULL),
	(88, 'GALIANA', 'null', NULL, NULL, NULL),
	(89, 'GENERAL', 'null', NULL, NULL, NULL),
	(90, 'GENERICO', 'null', NULL, NULL, NULL),
	(91, 'GENIUS', 'null', NULL, NULL, NULL),
	(92, 'GLOBAL WATER', 'null', NULL, NULL, NULL),
	(93, 'HACER', 'null', NULL, NULL, NULL),
	(94, 'HET RACK', 'null', NULL, NULL, NULL),
	(95, 'HP', 'null', NULL, NULL, NULL),
	(96, 'IEI', 'null', NULL, NULL, NULL),
	(97, 'INTEGRADO', 'null', NULL, NULL, NULL),
	(98, 'i-ONE', 'null', NULL, NULL, NULL),
	(99, 'KITT&ZONEN', 'null', NULL, NULL, NULL),
	(100, 'LABTEC', 'null', NULL, NULL, NULL),
	(101, 'LENOVO', 'null', NULL, NULL, NULL),
	(102, 'LINDE', 'null', NULL, NULL, NULL),
	(103, 'LOGITECH', 'null', NULL, NULL, NULL),
	(104, 'LYNX', 'null', NULL, NULL, NULL),
	(105, 'MAGEE SCIENTIFIC', 'null', NULL, NULL, NULL),
	(106, 'MESALABS', 'null', NULL, NULL, NULL),
	(107, 'MET ONE', 'null', NULL, NULL, NULL),
	(108, 'MICROSOFT', 'null', NULL, NULL, NULL),
	(109, 'MITSUBISHI', 'null', NULL, NULL, NULL),
	(110, 'MOD EUROPA', 'null', NULL, NULL, NULL),
	(111, 'MONITOR EUR', 'null', NULL, NULL, NULL),
	(112, 'MUS2P', 'null', NULL, NULL, NULL),
	(113, 'OLFER', 'null', NULL, NULL, NULL),
	(114, 'PARKER', 'null', NULL, NULL, NULL),
	(115, 'PERIXX', 'null', NULL, NULL, NULL),
	(116, 'PH SCHENK', 'null', NULL, NULL, NULL),
	(117, 'PHILIPS', 'null', NULL, NULL, NULL),
	(118, 'PRAXAIR', 'null', NULL, NULL, NULL),
	(119, 'PRIMAX', 'null', NULL, NULL, NULL),
	(120, 'ROTRONIC', 'null', NULL, NULL, NULL),
	(121, 'S4002-CM', 'null', NULL, NULL, NULL),
	(122, 'S4002PLUS', 'null', NULL, NULL, NULL),
	(123, 'SOLARTRON MOBREY', 'null', NULL, NULL, NULL),
	(124, 'SONY', 'null', NULL, NULL, NULL),
	(125, 'SYNSPEC  SPECTRA', 'null', NULL, NULL, NULL),
	(126, 'SYNSPECH', 'null', NULL, NULL, NULL),
	(127, 'TACENS', 'null', NULL, NULL, NULL),
	(128, 'TESTO', 'null', NULL, NULL, NULL),
	(129, 'TRUST', 'null', NULL, NULL, NULL),
	(130, 'ZAMBELLI', 'null', NULL, NULL, NULL);
