INSERT INTO `techniques` (`id`, `idtechnique`, `technique`, `created_at`, `updated_at`, `deleted_at`) VALUES
	(1, 0, 'Desconocido', NULL, NULL, NULL),
	(2, 2, 'Ionización Llama', NULL, NULL, NULL),
	(3, 5, 'Absorción Atómica', NULL, NULL, NULL),
	(4, 6, 'Absorción Ultravioleta', NULL, NULL, NULL),
	(5, 7, 'Absorcion de luz', NULL, NULL, NULL),
	(6, 8, 'Quimiluminiscencia', NULL, NULL, NULL),
	(7, 24, 'Humo Normalizado', NULL, NULL, NULL),
	(8, 38, 'Fluorescencia Ultravioleta', NULL, NULL, NULL),
	(9, 39, 'Thorina', NULL, NULL, NULL),
	(10, 40, 'Pararosanilina', NULL, NULL, NULL),
	(11, 46, 'Efecto Scatering', NULL, NULL, NULL),
	(12, 47, 'Microbalanza', NULL, NULL, NULL),
	(13, 48, 'Absorción Infrarroja', NULL, NULL, NULL),
	(14, 49, 'Absorción Beta', NULL, NULL, NULL),
	(15, 50, 'Gravimetría', NULL, NULL, NULL),
	(16, 51, 'Cromatografía Iónica', NULL, NULL, NULL),
	(17, 52, 'Gravimetría Fracción Solubre-Insoluble', NULL, NULL, NULL),
	(18, 53, 'Espectrofotometría', NULL, NULL, NULL),
	(19, 54, 'Nefelometría', NULL, NULL, NULL),
	(20, 55, 'Método azul de metileno', NULL, NULL, NULL),
	(21, 56, 'Potenciometría', NULL, NULL, NULL),
	(22, 57, 'Griess-Saltzman', NULL, NULL, NULL),
	(23, 58, 'Acidez Total', NULL, NULL, NULL),
	(24, 59, 'Cromatografía de Gases', NULL, NULL, NULL),
	(25, 60, 'Fenolato sódico', NULL, NULL, NULL),
	(26, 61, 'Culombimetría', NULL, NULL, NULL),
	(27, 89, 'Meteorología', NULL, NULL, NULL);
