INSERT INTO `units` (`id`, `unit`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES
	(1, 'µg/m³N', 'Microgramos metro cubico normal', NULL, NULL, NULL),
	(2, 'µg/m³', 'Microgramos metro cubico', NULL, NULL, NULL),
	(3, 'MW', 'Mega Watios', NULL, NULL, NULL),
	(4, 'ºC', 'Grados centigrados', NULL, NULL, NULL),
	(5, 'm³Nh', 'Metro cúbico por hora', NULL, NULL, NULL),
	(6, 'mg/m³', 'Miligramos por metro cúbico', NULL, NULL, NULL),
	(7, '%', 'Porcentaje', NULL, NULL, NULL),
	(8, 'Grd', 'Angulos sexagesimales', NULL, NULL, NULL),
	(9, 'm/s', 'Metros por sg', NULL, NULL, NULL),
	(10, 'mm', 'Milimetros', NULL, NULL, NULL),
	(11, 'Ly', 'Langley', NULL, NULL, NULL),
	(12, 'mmHg', 'Milimetros de mercurio', NULL, NULL, NULL),
	(13, 'µScm', 'Microsiemens por centimetro', NULL, NULL, NULL),
	(14, 'NTU', '--', NULL, NULL, NULL),
	(15, 'W/m²', 'Watios por metro cuadrado', NULL, NULL, NULL),
	(16, 'mbar', 'Milibares', NULL, NULL, NULL),
	(17, 'ppb', 'Partes por billon', NULL, NULL, NULL),
	(18, 'l/m²', 'Litros por metro cuadrado', NULL, NULL, NULL),
	(19, 'm³/s', 'Metros cúbicos por segundo', NULL, NULL, NULL),
	(20, 'm³/h', 'Metros cúbicos por hora', NULL, NULL, NULL),
	(21, 'W/cm²', 'Watios por centimetro cuadrado', NULL, NULL, NULL),
	(22, 'mg/l', 'Miligramos por litro', NULL, NULL, NULL),
	(23, 'MW/h', 'Mega Watios por hora', NULL, NULL, NULL),
	(24, 't', 'Toneladas', NULL, NULL, NULL),
	(25, 'gKWh', 'Grados por kilowatio hora', NULL, NULL, NULL),
	(26, 'm³NH2Om³A', 'm³ de H2O por m³ de aire seco', NULL, NULL, NULL),
	(27, 'kCalKWh', 'Kilocalorias por kilowatio hora', NULL, NULL, NULL),
	(28, 'Kgseg', 'Kilogramos por segundo', NULL, NULL, NULL),
	(29, 'bar', 'Bares', NULL, NULL, NULL),
	(30, 'NA', 'No Aplica', NULL, NULL, NULL),
	(31, 'Km/h', 'Kilometros por hora', NULL, NULL, NULL),
	(32, 'dBA', 'Decibelios', NULL, NULL, NULL),
	(33, 'ng/m³', 'Nanogramos metro cubico', NULL, NULL, NULL),
	(34, '\'% H.R.\'', 'Humedad relativa', NULL, NULL, NULL),
	(35, '\'mb\'\r\n', 'Presión barométrica', NULL, NULL, NULL),
	(36, '\'mg/m2\'\r\n', 'Miligramos por metro cuadrado', NULL, NULL, NULL),
	(37, '\'%molar\'', 'Masa molar', NULL, NULL, NULL),
	(38, '\'V\'', 'Voltios', NULL, NULL, NULL),
	(39, 'Desconocida', 'Desconocida', NULL, NULL, NULL),
	(40, '\'Nm3/Kg\'', 'Kilogramos por metro cúbico normal', NULL, NULL, NULL),
	(41, '\'cm\'', 'Centímetros', NULL, NULL, NULL),
	(42, '\'l/min\'', 'Litros por minuto', NULL, NULL, NULL),
	(43, 'mW/m²', 'Miliwatios metro cuadrado', NULL, NULL, NULL),
	(44, 'Kj/m²', 'Kilojulios por metro cuadrado', NULL, NULL, NULL),
	(45, 'Umol/mm2', 'Micromoles por milimetro al cuadrado', NULL, NULL, NULL),
	(46, 'Mmol/sm2', NULL, NULL, NULL, NULL),
	(47, 'ppm', NULL, NULL, NULL, NULL),
	(48, 'ABS/m', NULL, NULL, NULL, NULL),
	(50, 'mg/l C\r\n', NULL, NULL, NULL, NULL),
	(51, 'mg/l NO3', NULL, NULL, NULL, NULL),
	(52, 'ufc/100 ml', NULL, NULL, NULL, NULL),
	(53, 'u', NULL, NULL, NULL, NULL),
	(54, 'mV', 'Milivoltios', NULL, NULL, NULL),
	(55, 'm', 'Metros', NULL, NULL, NULL),
	(56, 'mg/l O2', NULL, NULL, NULL, NULL),
	(57, 'mg/l NO2', NULL, NULL, NULL, NULL),
	(58, 'mg/l HOCl', NULL, NULL, NULL, NULL),
	(59, 'Nm³/s', NULL, NULL, NULL, NULL),
	(61, 'Kg/h', 'Kilogramo por hora', NULL, NULL, NULL),
	(62, 'Pa', NULL, NULL, NULL, NULL),
	(63, 'º', 'Grados coordenadas', NULL, NULL, NULL),
	(64, 'MVA', NULL, NULL, NULL, NULL),
	(65, 'HRS', NULL, NULL, NULL, NULL),
	(66, 'Nm³/H', 'Metro cúbico normal por hora', NULL, NULL, NULL),
	(67, 'kWh/m³N', 'Kilowatioshora por metro cubico normal', NULL, NULL, NULL),
	(68, 'cm³/min', 'Centímetro cúbico por minuto', NULL, NULL, NULL);
